# Generated by Django 4.0.3 on 2022-05-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_merge_20220504_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.DateTimeField(null=True),
        ),
    ]
